version = 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -e .
  build:
    commands:
      - echo Build started on 'date'
      - pytest test_Calculator.py
      




  
