version = 0.2

phase:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -e .
  build:
    commands:
      - echo Build started on 'date'
      - pytest test_Calculator.py
      




  
